-- Auto-generated by install.sh; edit manually if needed.
-- List displays with: hyprctl monitors all
-- Example: hl.monitor({ output = "DP-1", mode = "2560x1440@165", position = "0x0", scale = 1 })

hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
